### ISSUE TITLE
DNU: Instance of WriteStream did not understand #inspectionFullString

### ISSUE THREAD

**Issue by tinchodias** [jordanmontt/illimani-memory-profiler#23]
Hi, 
Clicking on the GUI, I got:

<img width="1639" alt="Screenshot 2023-09-28 at 14 42 30" src="https://github.com/jordanmontt/illimani-memory-profiler/assets/3044265/fee1e090-261c-4d05-80df-f323daee0f33">

And DNU seems to be fixed when I inserted the send "contents" like this:
```
inspectorExtensionContextFingerprint: aBuilder
	<inspectorPresentationOrder: 2 title: 'Context Fingerprint'>

	^ contextFingerprint contents inspectionFullString
```

Please tell me if my bug description is not precise enough.

**Comment by jordanmontt** [comment]
Hi, I can't seem to reproduce the bug. Could you send me some code to reproduce it?

Thanks!

**Comment by tinchodias** [comment]
Ok I will revert my change and check.

BTW, thanks for the tool! I'm starting to spot optimizations:
https://github.com/pharo-graphics/Bloc/issues/320
https://github.com/pharo-graphics/Bloc/issues/321

**Comment by tinchodias** [comment]
I didn't say it, the cause of the DNU was that the object in "contextFingerprint" instvar was a WriteStream... does it tell something to you?

**Comment by jordanmontt** [comment]
Thanks for using the tool! And about the WriteStream you said it on the title. That is what actually seems weird for me because the method calls `contents` which it should return a String

**Comment by tinchodias** [comment]
Okay, but it was me who added "contents". Current source code doesn't has the "contents".

**Comment by tinchodias** [comment]
Sebastian,
If you want to reproduce it:
0. Open a Pharo 12
1. Install BlocBenchs as said in https://github.com/pharo-graphics/BlocBenchs/wiki
2. In a workspace, evaluate:
```
[ numberOfSeconds := 10.
IllAllocationProfiler new
	profileOn: [
		PCBenchmarkSuite new
			addCase: PCSolidCirclesBenchCase new;
			numberOfSeconds: numberOfSeconds;
			addAlexandrieBenchmarker;
			run.
		numberOfSeconds seconds wait. ];
	open ] fork
```
3. Click on tab Memory tab
4. Click on a table item
5. In the inspector, click on "Grouped Allocations" tab
6. Click on an item
7. Click on "Context Fingerprint" tab
8. You see the debugging message, in the inspector

**Comment by jordanmontt** [comment]
Great! I will dig into that tomorrow :)

**Comment by jordanmontt** [comment]
I have removed this implementation of context fingerprint.
