### ISSUE TITLE
Pharo 12 image unresponsive 

### ISSUE THREAD

**Issue by tinchodias** [jordanmontt/illimani-memory-profiler#24]
Hello. I loaded the project with:
```
EpMonitor disableDuring: [
	Metacello new
		baseline: 'IllimaniProfiler';
		repository: 'github://jordanmontt/illimani-memory-profiler:main';
		load ].
```
This is a snippet that reproduces it:
```
IllAllocationProfiler new
	profileFor: 1 seconds;
	open;
	yourself
```

But also copy-pasted scripts from readme, and a script that I used in the past for Bloc.

My Pharo has 1 or 2 weeks:

Pharo 12.0.0
Build information: Pharo-12.0.0+build.1058.sha.d7fe9c39709fd9c1855730743d80c4c7d49a116d (64 Bit)

Is this information enough?

**Comment by jordanmontt** [comment]
Hello Martin, sorry for the delay. I have fixed this issue for Pharo 12. The problem was the "contextFingerprint". I removed it, I will open a new issue for that

**Comment by tinchodias** [comment]
Great thanks
