### ISSUE TITLE
Add human readable size text

### ISSUE THREAD

**Issue by akevalion** [jordanmontt/illimani-memory-profiler#7]
![image](https://user-images.githubusercontent.com/10532890/220387885-4ff6adee-6ce8-4458-8796-a86b4edc05fb.png)

Please in total size in byte column use humanReadableSIByteSize or a similar method to express to users more meaningful information.

**Comment by jordanmontt** [comment]
Fixed on latest commit (875a52b0b3f52a60c0922b6f941b5b7199c86799)
